### ISSUE TITLE
docker image stops execution with an error

### ISSUE THREAD

**Issue by yonadav** [FreeFem/FreeFem-docker#3]
An attempt to execute the image in interactive mode failed with an error about ls /data/*.edp path /data does not exist.
the command is in the dockerfile and passed to the image as an initialization command.
/data does not exist in the image, on any case executing the command bash -C [command] would run the command and exit so no interactive mode is possible (even if /data existed in the image).

after modifying the command in the json file within the image to have "Cmd": ["bash"] solved the problem and I have an interactive mode

**Comment by prj-** [comment]
The last command of the Dockerfile is not appropriate anymore. It was used at the very beginning, but we've since then modified it quite substantially. Would you mind create a pull request with your changes, please? @sgarnotel or myself will then review and merge it. Thanks in advance.

**Comment by yonadav** [comment]
I am inspecting the master branch (the same applies for tag v4.5)
https://github.com/FreeFem/FreeFem-docker/blob/4a9a1acd08f779f703d006511d08bc89439538bc/freefem-docker/Dockerfile#L84

In the last line there is a command that bash should execute:
'CMD ["bash", "-c", "ls /data/$GLOB | xargs -I {} ff-mpirun -n 1 {}"]'
The same command is in a json file on the root of the image file, I actually modified the json file and repacked my copy of the tar file  image.
I am far from being an expert in dockers, my guess is that the command is copied from the Dockerfile to the json file when the image is generated.
Thanks

**Comment by prj-** [comment]
Could you create a PR with your changes to `Dockerfile`, please?

**Comment by sgarnotel** [comment]
You can access the docker image without launch this command, just do it:
```
docker run -t -i freefem/freefem bash
```

**Comment by yonadav** [comment]
Thanks @sgarnotel 
I simply followed the instructions in:
[](https://github.com/FreeFem/FreeFem-docker/blob/master/README.md)
and had the problem
by using:
`docker run -ti freefem bash`
The problem is bypassed.

**Comment by sgarnotel** [comment]
@yonadav I modified the README, effectively it was wrong
