### ISSUE TITLE
run *.edp broken

### ISSUE THREAD

**Issue by siogwah** [FreeFem/FreeFem-docker#4]
running 
docker run -v $(pwd):/data freefem

results in 
xargs: ff-mpirun: No such file or directory

the path is not included in the Dockerfile CMD statement

CMD ["bash", "-c", "ls /data/$GLOB | xargs -I {} ff-mpirun -n 1 {}"]
   this is same for v4.4, v4.4.2, v4.4-3 and v4.5

v4.2.1 used
CMD ["bash", "-c", "ls /data/$GLOB | xargs -I {} /usr/freefem/bin/FreeFem++ {}"]

**Comment by prj-** [comment]
Thanks, this should be fixed now. Sorry for the late answer.

**Comment by siogwah** [comment]
no worries
